server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://10.178.0.20:8761/eureka/
    enabled: true

product-api:
  ribbon:
    ConnectTimeout: 500
    ReadTimeout: 3000